### ISSUE TITLE
A little question about jetifier

### ISSUE THREAD

**Issue by lucianomlima** [mikehardy/rnfbdemo#3]
I get some problems on CI (Bitrise) during build with RN 0.61.5 and RNFirebase 5x, like the following:
```bash
> Task :react-native-firebase:compileReleaseJavaWithJavac FAILED
/Users/luciano/projetos/app/sanarflix-app-v2/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/React
NativeFirebaseAppRegistrar.java:20: error: package android.support.annotation does not exist
import android.support.annotation.Keep;
```
Looking here, I see that you call `npx jetifier` before the gradle build.
Is this required with RNFirebase 5x? Shouldn't RN 0.60+ run jetifier automatically?
It's only to understand.

**Comment by mikehardy** [comment]
in RN60+ the react-native CLI automatically calls in to jetifier on android build, so it should not be necessary to make an explicit call

If I'm doing so in the demo it might just be a remnant from cloning my first demo (RN59, where you must explicitly call it) to future versions.

So yes - for RN59, explicit npx jetifier is needed, RN60+, it is called automatically for you

**Comment by lucianomlima** [comment]
I'm not using RN 0.59, i'm using RN 0.61.5 and with RN Firebase 5x I need to call `npx jetifier` to convert lot of classes to get a successful build.
I can reproduce in my machine and in Bitrise CI. build success only when running jetifier before build.

**Comment by mikehardy** [comment]
Interesting. Still not a bug with jetifier, per se. And what jetifier does is idempotent - you can run it as many times as you like and it will have the same result, so even if you add the calls to jetifier before the build to get it working now and then later on the CLI calls it automatically (as it should) it won't harm anything and it's fast enough it shouldn't matter. There's something strange about the setup though, what you describe shouldn't happen

**Comment by lucianomlima** [comment]
Yeah. First happen on my CI. I get some time to understand and reproduce on my machine.
If I delete `node_modules`, run yarn and run build (without the jetifier) I get the same error from there.
Running jetifier and build again, works properly. I don't try with RN Firebase v6.
